runtime: python27
api_version: 1
threadsafe: true

#since 
handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /.*
  script: main.app
  secure: always

#this is where we need to add libraries in our app.yaml page. For this case we are using jinja2.0
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
